# Generated by Django 2.0.4 on 2018-04-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fightgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combat',
            options={'verbose_name': 'Combate', 'verbose_name_plural': 'Combates'},
        ),
        migrations.AddField(
            model_name='combat',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combat_winner', to='fightgame.Fighter', verbose_name='Ganador'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.IntegerField(choices=[(0, 'Pluma'), (1, 'Medio'), (2, 'Pesado')], default=0, verbose_name='Categoría'),
        ),
    ]
